Step 1. Data Collection & Preprocessing

Step 1A: Data Collection

In [1]:
# !pip install pymatgen matminer pandas scikit-learn numpy

In [1]:
import pandas as pd
import numpy as np

from mp_api.client import MPRester
from pymatgen.core import Composition

from matminer.featurizers.composition import (
    ElementProperty,
    Stoichiometry,
    IonProperty
)

from sklearn.preprocessing import StandardScaler

In [17]:
# Export MP API key
!pip install python-dotenv

from dotenv import load_dotenv
import os

load_dotenv()

MP_API_KEY = os.getenv("MP_API_KEY")

if MP_API_KEY is None:
    raise RuntimeError("MP_API_KEY not found. Check your .env file.")

print("MP API key loaded successfully")

Requirement already satisfied: python-dotenv in /home/mostaq/anaconda3/lib/python3.11/site-packages (0.21.0)
MP API key loaded successfully

In [3]:
# Query data from MP
with MPRester(MP_API_KEY) as mpr:
    results = mpr.materials.summary.search(
        # formula="*O6",
        elements=["O"],
        num_elements=4,
        energy_above_hull=(0, 0.05),
        fields=[
            "material_id",
            "formula_pretty",
            "structure",
            "band_gap",
            "energy_above_hull"
        ],
        chunk_size=1000
    )

records = [r.dict() for r in results]

df_raw = pd.DataFrame(records)
df_raw.head()

Retrieving SummaryDoc documents:   0%|          | 0/14987 [00:00<?, ?it/s]

,formula_pretty,material_id,structure,energy_above_hull,band_gap,fields_not_requested
0,LiV4OF11,mp-coymj,"{'@module': 'pymatgen.core.structure', '@class...",0.048778,0.8691,"[builder_meta, nsites, elements, nelements, co..."
1,Li4Co2OF7,mp-cvylq,"{'@module': 'pymatgen.core.structure', '@class...",0.035992,1.3217,"[builder_meta, nsites, elements, nelements, co..."
2,LiV3OF11,mp-cwjvl,"{'@module': 'pymatgen.core.structure', '@class...",0.035008,1.8749,"[builder_meta, nsites, elements, nelements, co..."
3,Li2VOF4,mp-cwsdh,"{'@module': 'pymatgen.core.structure', '@class...",0.008264,2.0691,"[builder_meta, nsites, elements, nelements, co..."
4,BaVOF4,mp-bmfcj,"{'@module': 'pymatgen.core.structure', '@class...",0.013113,2.4971,"[builder_meta, nsites, elements, nelements, co..."

In [4]:
print(df_raw.columns.tolist())
# Expected Output: ['formula_pretty', 'material_id', 'structure', 'energy_above_hull', 'band_gap', 'fields_not_requested']

['formula_pretty', 'material_id', 'structure', 'energy_above_hull', 'band_gap', 'fields_not_requested']

In [7]:
from pymatgen.core import Composition

# Typical A-site elements in oxide perovskites
A_SITE_ELEMENTS = {
    "Li", "Na", "K", "Rb", "Cs",
    "Mg", "Ca", "Sr", "Ba",
    "La", "Ce", "Pr", "Nd", "Sm", "Gd", "Y"
}

# Elements that form polyatomic oxyanions (exclude them)
NETWORK_FORMERS = {
    "Si", "Ge", "P", "S", "B", "As", "Se", "Te"
}

def is_double_perovskite_relaxed(formula):
    try:
        comp = Composition(formula)
        el_amt = comp.get_el_amt_dict()

        # Must have exactly 4 elements
        if len(el_amt) != 4:
            return False

        # Must have exactly O6
        if el_amt.get("O", 0) != 6:
            return False

        # Separate cations
        cations = {el: amt for el, amt in el_amt.items() if el != "O"}
        counts = sorted(cations.values())

        # Must match A2BB′
        if counts != [1, 1, 2]:
            return False

        # Identify A-site (count = 2)
        A_elements = [el for el, amt in cations.items() if amt == 2]
        if len(A_elements) != 1:
            return False

        A = A_elements[0]

        # A-site chemical validity
        if A not in A_SITE_ELEMENTS:
            return False

        # Exclude silicates, germanates, phosphates, etc.
        for el in cations:
            if el in NETWORK_FORMERS:
                return False

        return True

    except Exception:
        return False

In [8]:
df_dp = df_raw[df_raw["formula_pretty"].apply(is_double_perovskite_relaxed)]
df_dp = df_dp.reset_index(drop=True)

print("Double perovskites found:", len(df_dp))
df_dp[["material_id", "formula_pretty", "band_gap"]].head()

Double perovskites found: 868

  material_id formula_pretty  band_gap
0    mp-cukko       Ba2FeWO6    2.5062
1    mp-cuols      Ba2MnNbO6    1.1475
2    mp-cuyes      Sr2MnNbO6    1.7479
3    mp-cvicr      Ba2FeMoO6    0.7715
4    mp-cviuc      Ba2FeMoO6    0.9037

Step 1B: Target Cleaning
Remove missing band gaps
Remove metallic entries (Eg = 0)

In [9]:
# Step 1B: Clean band gap data

df_ml = df_dp.copy()

# Remove missing band gaps
df_ml = df_ml[df_ml["band_gap"].notnull()]

# Remove metallic systems (Eg = 0)
df_ml = df_ml[df_ml["band_gap"] > 0]

df_ml = df_ml.reset_index(drop=True)

print("Samples after band-gap cleaning:", len(df_ml))
df_ml[["material_id", "formula_pretty", "band_gap"]].head()

Samples after band-gap cleaning: 574

  material_id formula_pretty  band_gap
0    mp-cukko       Ba2FeWO6    2.5062
1    mp-cuols      Ba2MnNbO6    1.1475
2    mp-cuyes      Sr2MnNbO6    1.7479
3    mp-cvicr      Ba2FeMoO6    0.7715
4    mp-cviuc      Ba2FeMoO6    0.9037

STEP 1C — Feature engineering
Convert formula → composition
Generate Magpie descriptors
Save feature matrix

In [10]:
df_ml["composition"] = df_ml["formula_pretty"].apply(Composition)
df_ml[["formula_pretty", "composition"]].head()

  formula_pretty      composition
0       Ba2FeWO6   (Ba, Fe, W, O)
1      Ba2MnNbO6  (Ba, Mn, Nb, O)
2      Sr2MnNbO6  (Sr, Mn, Nb, O)
3      Ba2FeMoO6  (Ba, Fe, Mo, O)
4      Ba2FeMoO6  (Ba, Fe, Mo, O)

In [13]:
from matminer.featurizers.composition import ElementProperty

ep = ElementProperty.from_preset(
    "magpie",
    impute_nan=True
)

X = ep.featurize_dataframe(
    df_ml,
    col_id="composition",
    ignore_errors=True
)

y = df_ml["band_gap"]

print("Feature matrix shape:", X.shape)
print("NaNs in features:", X.isna().sum().sum())

ElementProperty:   0%|          | 0/574 [00:00<?, ?it/s]

Feature matrix shape: (574, 139)
NaNs in features: 0

In [14]:
# Drop non-feature columns
non_feature_cols = [
    "material_id",
    "formula_pretty",
    "structure",
    "composition",
    "band_gap"
]

X_ml = X.drop(columns=[c for c in non_feature_cols if c in X.columns])

print("Final ML feature shape:", X_ml.shape)

Final ML feature shape: (574, 134)

In [15]:
import joblib

joblib.dump(X_ml, "dp_magpie_features.pkl")
joblib.dump(y, "dp_bandgap_targets.pkl")

print("Step 1 completed: features and targets saved.")

Step 1 completed: features and targets saved.