In [33]:
import pandas as pd

df = pd.read_csv("ga_solar_relevant_candidates.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   generation                  49 non-null     int64
 1   candidate                   49 non-null     object
 2   formula                     49 non-null     object
 3   A                           49 non-null     object
 4   B                           49 non-null     object
 5   B_prime                     49 non-null     object
 6   fitness                     49 non-null     float64
 7   predicted_band_gap          49 non-null     float64
 8   predicted_ehull             49 non-null     float64
 9   predicted_formation_energy  49 non-null     float64
 10  charge_neutral              49 non-null     bool
dtypes: bool(1), float64(4), int64(1), object(5)
memory usage: 4.0+ KB

In [15]:
from dotenv import load_dotenv
import os

load_dotenv()

MP_API_KEY = os.getenv("MP_API_KEY")

if MP_API_KEY is None:
    raise RuntimeError("MP_API_KEY not found. Check your .env file.")

print("MP API key loaded successfully")

MP API key loaded successfully

In [37]:
formula_data = df[df["formula"] == candidate_formulas[1]]
formula_data.A

1    Sr
Name: A, dtype: object

In [48]:
from mp_api.client import MPRester
from pymatgen.core import Composition
import pandas as pd

candidate_formulas = df.formula.tolist()

mp_records = []

with MPRester(MP_API_KEY) as mpr:
    for formula in candidate_formulas:
        target_comp = Composition(formula).reduced_composition

        docs = mpr.materials.summary.search(
            formula=formula
        )

        exact_matches = []
        for d in docs:
            if d.composition_reduced == target_comp:
                exact_matches.append(d)

        if not exact_matches:
            formula_data = df[df["formula"] == formula].iloc[0]
            mp_records.append({
                "formula": formula,
                "A": formula_data.A,
                "B": formula_data.B,
                "B_prime" : formula_data.B_prime,
                "fitness" : formula_data.fitness,
                "predicted_band_gap" : formula_data.predicted_band_gap,
                "predicted_ehull" : formula_data.predicted_ehull,         
                "predicted_formation_energy":  formula_data.predicted_formation_energy,
                "charge_neutral" : formula_data.charge_neutral,
            })

novel_candidates= pd.DataFrame(mp_records)
novel_candidates.to_csv("ga_candidates_mp_existence_check.csv", index=False)

novel_candidates

Retrieving SummaryDoc documents:   0%|          | 0/2 [00:00<?, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/3 [00:00<?, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/4 [00:00<?, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/2 [00:00<?, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/2 [00:00<?, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/6 [00:00<?, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/2 [00:00<?, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/5 [00:00<?, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

      formula   A  ... predicted_formation_energy charge_neutral
0    Sr2VNiO6  Sr  ...                  -2.818743           True
1   Sr2TaNiO6  Sr  ...                  -2.870783           True
2   Sr2NbTiO6  Sr  ...                  -3.094176           True
3   Ca2NbTiO6  Ca  ...                  -3.098697           True
4    Sr2CrVO6  Sr  ...                  -3.035544           True
5   Ba2NbTiO6  Ba  ...                  -3.056940           True
6     K2VCrO6   K  ...                  -2.948456           True
7    Sr2NbVO6  Sr  ...                  -3.078544           True
8    Rb2CrVO6  Rb  ...                  -2.950093           True
9   Ca2CrMoO6  Ca  ...                  -2.652523           True
10    Y2VNiO6   Y  ...                  -2.783292           True
11   Y2TiCrO6   Y  ...                  -3.171634           True
12  Sr2NbNiO6  Sr  ...                  -2.780452           True
13  Sr2MoHfO6  Sr  ...                  -3.122523           True
14   Ca2NbVO6  Ca  ...                  -3.078569           True
15   Ca2VMnO6  Ca  ...                  -3.042690           True
16  Na2MoZrO6  Na  ...                  -2.998176           True
17  Ca2CrMnO6  Ca  ...                  -2.879920           True
18   Sr2FeVO6  Sr  ...                  -2.963566           True
19   Sr2WTiO6  Sr  ...                  -2.909400           True
20    Y2VCuO6   Y  ...                  -2.782360           True
21  Ca2NbNiO6  Ca  ...                  -2.754183           True
22  Ba2TaNiO6  Ba  ...                  -2.876744           True
23  Sr2CrNiO6  Sr  ...                  -2.652969           True
24  Rb2CrMnO6  Rb  ...                  -2.808413           True
25  Cs2CrMnO6  Cs  ...                  -2.820982           True
26  Sr2CuCrO6  Sr  ...                  -2.638313           True
27   Ca2VCoO6  Ca  ...                  -2.808606           True
28    K2VMoO6   K  ...                  -2.915541           True
29   Y2MnTiO6   Y  ...                  -3.268759           True
30  Ca2MoSnO6  Ca  ...                  -2.559406           True
31   Ba2WSbO6  Ba  ...                  -2.526419           True
32  Rb2SnMoO6  Rb  ...                  -2.324042           True
33  La2HfCuO6  La  ...                  -3.167313           True
34  Ca2MoInO6  Ca  ...                  -2.610899           True
35   Y2HfNiO6   Y  ...                  -3.159681           True

[36 rows x 9 columns]

In [58]:
import numpy as np
from pymatgen.core.periodic_table import Species, Element

R_O = 1.40  # Shannon radius for O2- in octahedral coordination, approximate

OXIDATION_STATES_CHOSEN = {
    "Li": 1, "Na": 1, "K": 1, "Rb": 1, "Cs": 1,
    "Mg": 2, "Ca": 2, "Sr": 2, "Ba": 2,
    "La": 3, "Y": 3,

    "Al": 3, "Ga": 3, "In": 3,
    "Ti": 4, "V": 5, "Cr": 3, "Mn": 4,
    "Fe": 3, "Co": 3, "Ni": 3, "Cu": 2,
    "Zn": 2, "Zr": 4, "Hf": 4,
    "Nb": 5, "Ta": 5,
    "Mo": 6, "W": 6,
    "Sn": 4, "Sb": 5, "Bi": 3
}


def get_ionic_radius(element, oxidation_state, coordination):
    # First try Shannon radius with coordination number
    try:
        sp = Species(element, oxidation_state)
        r = sp.get_shannon_radius(cn=coordination)
        if r is not None:
            return r
    except Exception:
        pass

    # Fallback: use pymatgen ionic radii dictionary
    try:
        radii_dict = Element(element).ionic_radii
        r = radii_dict.get(oxidation_state)
        if r is not None:
            return float(r)
    except Exception:
        pass

    return np.nan


def tolerance_octahedral_factors(A, B, Bp):
    ox_A = OXIDATION_STATES_CHOSEN.get(A)
    ox_B = OXIDATION_STATES_CHOSEN.get(B)
    ox_Bp = OXIDATION_STATES_CHOSEN.get(Bp)

    if ox_A is None or ox_B is None or ox_Bp is None:
        return np.nan, np.nan

    # A-site: 12-fold coordination, B-sites: 6-fold coordination
    rA = get_ionic_radius(A, ox_A, 12)
    rB = get_ionic_radius(B, ox_B, 6)
    rBp = get_ionic_radius(Bp, ox_Bp, 6)

    if np.isnan(rA) or np.isnan(rB) or np.isnan(rBp):
        return np.nan, np.nan

    rB_avg = (rB + rBp) / 2

    t = (rA + R_O) / (np.sqrt(2) * (rB_avg + R_O))
    mu = rB_avg / R_O

    return t, mu

In [59]:
df.info()
novel_candidates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   generation                  49 non-null     int64
 1   candidate                   49 non-null     object
 2   formula                     49 non-null     object
 3   A                           49 non-null     object
 4   B                           49 non-null     object
 5   B_prime                     49 non-null     object
 6   fitness                     49 non-null     float64
 7   predicted_band_gap          49 non-null     float64
 8   predicted_ehull             49 non-null     float64
 9   predicted_formation_energy  49 non-null     float64
 10  charge_neutral              49 non-null     bool
dtypes: bool(1), float64(4), int64(1), object(5)
memory usage: 4.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   formula                     36 non-null     object
 1   A                           36 non-null     object
 2   B                           36 non-null     object
 3   B_prime                     36 non-null     object
 4   fitness                     36 non-null     float64
 5   predicted_band_gap          36 non-null     float64
 6   predicted_ehull             36 non-null     float64
 7   predicted_formation_energy  36 non-null     float64
 8   charge_neutral              36 non-null     bool
dtypes: bool(1), float64(4), object(4)
memory usage: 2.4+ KB

In [60]:
df_screened = novel_candidates.copy()

t_values = []
mu_values = []

for _, row in df_screened.iterrows():
    t, mu = tolerance_octahedral_factors(
        row["A"],
        row["B"],
        row["B_prime"]
    )
    t_values.append(t)
    mu_values.append(mu)

df_screened["tolerance_factor_t"] = t_values
df_screened["octahedral_factor_mu"] = mu_values

df_screened["passes_geometry_screen"] = (
    (df_screened["tolerance_factor_t"] >= 0.80) &
    (df_screened["tolerance_factor_t"] <= 1.05) &
    (df_screened["octahedral_factor_mu"] >= 0.414) &
    (df_screened["octahedral_factor_mu"] <= 0.732)
)

df_screened.to_csv("ga_candidates_with_geometry_screen.csv", index=False)

df_screened[
    [
        "formula",
        "fitness",
        "predicted_band_gap",
        "predicted_ehull",
        "tolerance_factor_t",
        "octahedral_factor_mu",
        "passes_geometry_screen"
    ]
].head(36)

      formula   fitness  ...  octahedral_factor_mu  passes_geometry_screen
0    Sr2VNiO6  0.021044  ...              0.507143                    True
1   Sr2TaNiO6  0.029423  ...              0.542857                    True
2   Sr2NbTiO6  0.036314  ...              0.544643                    True
3   Ca2NbTiO6  0.053067  ...              0.544643                    True
4    Sr2CrVO6  0.056602  ...                   NaN                   False
5   Ba2NbTiO6  0.087582  ...              0.544643                    True
6     K2VCrO6  0.110257  ...                   NaN                   False
7    Sr2NbVO6  0.125119  ...              0.521429                    True
8    Rb2CrVO6  0.126594  ...                   NaN                   False
9   Ca2CrMoO6  0.131063  ...                   NaN                   False
10    Y2VNiO6  0.145040  ...              0.507143                    True
11   Y2TiCrO6  0.154981  ...                   NaN                   False
12  Sr2NbNiO6  0.161411  ...              0.542857                    True
13  Sr2MoHfO6  0.180945  ...              0.564286                    True
14   Ca2NbVO6  0.182654  ...              0.521429                    True
15   Ca2VMnO6  0.188353  ...                   NaN                   False
16  Na2MoZrO6  0.196361  ...              0.567857                    True
17  Ca2CrMnO6  0.211496  ...                   NaN                   False
18   Sr2FeVO6  0.224637  ...              0.523214                    True
19   Sr2WTiO6  0.226083  ...              0.530357                    True
20    Y2VCuO6  0.228519  ...              0.553571                   False
21  Ca2NbNiO6  0.230562  ...              0.542857                    True
22  Ba2TaNiO6  0.236594  ...              0.542857                    True
23  Sr2CrNiO6  0.237982  ...                   NaN                   False
24  Rb2CrMnO6  0.239396  ...                   NaN                   False
25  Cs2CrMnO6  0.246966  ...                   NaN                   False
26  Sr2CuCrO6  0.260241  ...                   NaN                   False
27   Ca2VCoO6  0.267705  ...              0.510714                    True
28    K2VMoO6  0.288973  ...              0.503571                    True
29   Y2MnTiO6  0.299408  ...                   NaN                   False
30  Ca2MoSnO6  0.348726  ...              0.557143                    True
31   Ba2WSbO6  0.375316  ...              0.535714                    True
32  Rb2SnMoO6  0.439195  ...              0.557143                    True
33  La2HfCuO6  0.456086  ...              0.614286                    True
34  Ca2MoInO6  0.458582  ...              0.596429                    True
35   Y2HfNiO6  0.464803  ...              0.567857                   False

[36 rows x 7 columns]

In [63]:
# Chemical confirmation
PREFERRED_OXIDATION_STATES = {
    "Li": [1], "Na": [1], "K": [1], "Rb": [1], "Cs": [1],
    "Mg": [2], "Ca": [2], "Sr": [2], "Ba": [2],
    "La": [3], "Y": [3],

    "Al": [3], "Ga": [3], "In": [3],
    "Ti": [4],
    "V": [3, 4, 5],
    "Cr": [3, 4],
    "Mn": [2, 3, 4],
    "Fe": [2, 3],
    "Co": [2, 3],
    "Ni": [2, 3],
    "Cu": [1, 2],
    "Zn": [2],
    "Zr": [4],
    "Hf": [4],
    "Nb": [5],
    "Ta": [5],
    "Mo": [4, 5, 6],
    "W": [5, 6],
    "Sn": [4],
    "Sb": [5],
    "Bi": [3, 5]
}

SUSPICIOUS_OXIDATION_STATES = {
    ("Ni", 4),
    ("Cu", 3),
    ("Co", 4),
    ("Fe", 4),
    ("Cr", 6),
    ("Mn", 7),
    ("Sn", 2),
    ("Sb", 3),
    ("Bi", 5)
}

In [64]:
def get_plausible_oxidation_combinations(A, B, Bp):
    combos = []

    for ox_A in PREFERRED_OXIDATION_STATES.get(A, []):
        for ox_B in PREFERRED_OXIDATION_STATES.get(B, []):
            for ox_Bp in PREFERRED_OXIDATION_STATES.get(Bp, []):

                if 2 * ox_A + ox_B + ox_Bp != 12:
                    continue

                suspicious_count = 0

                if (A, ox_A) in SUSPICIOUS_OXIDATION_STATES:
                    suspicious_count += 1
                if (B, ox_B) in SUSPICIOUS_OXIDATION_STATES:
                    suspicious_count += 1
                if (Bp, ox_Bp) in SUSPICIOUS_OXIDATION_STATES:
                    suspicious_count += 1

                combos.append({
                    "ox_A": ox_A,
                    "ox_B": ox_B,
                    "ox_B_prime": ox_Bp,
                    "suspicious_count": suspicious_count
                })

    return combos

In [65]:
plausibility_results = []

for _, row in df_screened.iterrows():
    combos = get_plausible_oxidation_combinations(
        row["A"],
        row["B"],
        row["B_prime"]
    )

    if len(combos) == 0:
        plausibility_results.append({
            "has_plausible_oxidation": False,
            "best_ox_A": None,
            "best_ox_B": None,
            "best_ox_B_prime": None,
            "suspicious_count": None
        })
    else:
        best_combo = sorted(combos, key=lambda x: x["suspicious_count"])[0]

        plausibility_results.append({
            "has_plausible_oxidation": best_combo["suspicious_count"] == 0,
            "best_ox_A": best_combo["ox_A"],
            "best_ox_B": best_combo["ox_B"],
            "best_ox_B_prime": best_combo["ox_B_prime"],
            "suspicious_count": best_combo["suspicious_count"]
        })

plausibility_df = pd.DataFrame(plausibility_results)

df_screened = pd.concat(
    [df_screened.reset_index(drop=True), plausibility_df],
    axis=1
)

In [71]:
df_dft_ready = df_screened[
    (df_screened["passes_geometry_screen"] == True) &
    (df_screened["has_plausible_oxidation"] == True)
].copy()

df_dft_ready = df_dft_ready.sort_values(
    by=["fitness", "predicted_ehull"],
    ascending=[True, True]
).reset_index(drop=True)

df_dft_ready[
    [
        "formula",
        "fitness",
        "predicted_band_gap",
        "predicted_ehull",
        "tolerance_factor_t",
        "octahedral_factor_mu",
        "best_ox_A",
        "best_ox_B",
        "best_ox_B_prime"
    ]
].head(17)

      formula   fitness  ...  best_ox_B  best_ox_B_prime
0    Sr2VNiO6  0.021044  ...        5.0              3.0
1   Sr2TaNiO6  0.029423  ...        5.0              3.0
2    Sr2NbVO6  0.125119  ...        5.0              3.0
3     Y2VNiO6  0.145040  ...        3.0              3.0
4   Sr2NbNiO6  0.161411  ...        5.0              3.0
5   Sr2MoHfO6  0.180945  ...        4.0              4.0
6    Ca2NbVO6  0.182654  ...        5.0              3.0
7   Na2MoZrO6  0.196361  ...        6.0              4.0
8    Sr2FeVO6  0.224637  ...        3.0              5.0
9   Ca2NbNiO6  0.230562  ...        5.0              3.0
10  Ba2TaNiO6  0.236594  ...        5.0              3.0
11   Ca2VCoO6  0.267705  ...        5.0              3.0
12    K2VMoO6  0.288973  ...        4.0              6.0
13  Ca2MoSnO6  0.348726  ...        4.0              4.0
14  Rb2SnMoO6  0.439195  ...        4.0              6.0
15  La2HfCuO6  0.456086  ...        4.0              2.0
16  Ca2MoInO6  0.458582  ...        5.0              3.0

[17 rows x 9 columns]